services:
  27chart:
    pull_policy: build
    network_mode: "host"
    build:
      context: .
    image: 27chart:latest
    container_name: 27chart
    environment:
      - TWITTER_ACCESS_TOKEN=$TWITTER_ACCESS_TOKEN
      - TWITTER_ACCESS_TOKEN_SECRECT=$TWITTER_ACCESS_TOKEN_SECRECT
      - TWITTER_CONSUMER_KEY=$TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_KEY_SECRET=$TWITTER_CONSUMER_KEY_SECRET
      - TWTTER_BEARER_TOKEN=$TWITTER_BEARER_TOKEN
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_NAME=$DB_NAME
      - PGPASSWORD=$PGPASSWORD
      - GDRIVE_CLIENT_SECRET_PATH=$GDRIVE_CLIENT_SECRET_PATH
      - GDRIVE_CREDENTIALS_PATH=$GDRIVE_CREDENTIALS_PATH
      - GDRIVE_SONGS_PATH=$GDRIVE_SONGS_PATH
      - GDRIVE_BACKUPS_PATH=$GDRIVE_BACKUPS_PATH
      - FALLBACK_PROXY_URL=$FALLBACK_PROXY_URL
      - SELENIUM_HOST=$SELENIUM_HOST
    volumes:
      - /data/27chart:/data/27chart
